/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <AudioClkGen.h>
#include <AudioClkGen_Ref.h>
#include <isr_InDMADone.h>
#include <USBInDMA_dma.h>
#include <Status_Reg_1.h>
#include <SystemTickTimer.h>
#include <isr_Tick.h>
#include <OA1m_aliases.h>
#include <OA1m.h>
#include <Clock_CIC.h>
#include <RxDMA_dma.h>
#include <isr_RxDMADone.h>
#include <USBFS.h>
#include <USBFS_audio.h>
#include <USBFS_cdc.h>
#include <USBFS_hid.h>
#include <USBFS_midi.h>
#include <USBFS_pvt.h>
#include <Opamp_2.h>
#include <OA2m_aliases.h>
#include <OA2m.h>
#include <OA3m_aliases.h>
#include <OA3m.h>
#include <Opamp_1.h>
#include <OA2o_aliases.h>
#include <OA2o.h>
#include <C2o_aliases.h>
#include <C2o.h>
#include <C0o_aliases.h>
#include <C0o.h>
#include <OA3o_aliases.h>
#include <OA3o.h>
#include <Opamp_3.h>
#include <LED_sink_aliases.h>
#include <LED_sink.h>
#include <C3o_aliases.h>
#include <C3o.h>
#include <Comp_0.h>
#include <Sample_Hold_0.h>
#include <OA0m_aliases.h>
#include <OA0m.h>
#include <Opamp_0.h>
#include <Sample_Hold_1.h>
#include <Comp_1.h>
#include <Sample_Hold_2.h>
#include <Comp_2.h>
#include <Sample_Hold_3.h>
#include <Comp_3.h>
#include <C1o_aliases.h>
#include <C1o.h>
#include <OA1o_aliases.h>
#include <OA1o.h>
#include <OA0o_aliases.h>
#include <OA0o.h>
#include <DMA_8to16_dma.h>
#include <Pin_6a_aliases.h>
#include <Pin_6a.h>
#include <Pin_12a_aliases.h>
#include <Pin_12a.h>
#include <Clock_CIC_Running.h>
#include <AudioClkGen_Clock_SCK.h>
#include <AudioClkGen_Clock_I2S.h>
#include <USBFS_Dm_aliases.h>
#include <USBFS_Dm.h>
#include <USBFS_Dp_aliases.h>
#include <USBFS_Dp.h>
#include <USBFS_ep2_dma.h>
#include <USBFS_ep6_dma.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

